name = "bot"
main = "src/index.js"
compatibility_date = "2024-03-20"

[vars]
TELEGRAM_API_URL = "https://api.telegram.org"
OEPNAI_API_MODEL = "gpt-3.5-turbo-0613"
OPENAI_API_URL = "https://api.wangyingzhe.cloud/v1/"


[[kv_namespaces]]
binding = "bot"
id = "6f45683a3bc84dd0b89323da2a7b0052"