name = "bot"
main = "src/index.js"
compatibility_date = "2024-03-20"

[vars]

TELEGRAM_API_URL = "https://api.telegram.org"

OEPNAI_API_MODEL = "gpt-3.5-turbo-1106"
OPENAI_API_URL = "https://api.wangyingzhe.cloud/v1/"
